version: '3.3'

networks:
  app-tier:
    driver: bridge

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'fleetmetrics-mgo'
    volumes:
      - ./.data/mongo:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-tier
  gateway:
    container_name: fleetmetrics-gateway
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      MQTT_PORT: ${GATEWAY_MQTT_PORT}
      MONGO_PORT: ${GATEWAY_MONGO_PORT}
      MONGO_SERVER: ${GATEWAY_MONGO_SERVER}
      MONGO_DATABASE: ${GATEWAY_MONGO_DATABASE}
      IO_PORT: ${GATEWAY_IO_PORT}
      API_PORT: ${GATEWAY_API_PORT}
    ports:
      - '${GATEWAY_MQTT_PORT}:${GATEWAY_MQTT_PORT}'
      - '${GATEWAY_API_PORT}:${GATEWAY_API_PORT}'
      - '${GATEWAY_IO_PORT}:${GATEWAY_IO_PORT}'
    volumes:
      - ./server/:/app
    depends_on:
      - mongodb
    networks:
      - app-tier
  spa:
    container_name: fleetmetrics-spa
    build: 
      context: .
      dockerfile: ./spa/Dockerfile
      args:
        FONTAWESOME_TOKEN: ${FONTAWESOME_TOKEN}
        PORT: ${SPA_PORT}
    ports:
      - '${SPA_PORT}:${SPA_PORT}'
    environment:
      REACT_APP_GATEWAY_IO_HOST: localhost
      REACT_APP_GATEWAY_IO_PORT: ${GATEWAY_IO_PORT}
      REACT_APP_GATEWAY_API_HOST: localhost
      REACT_APP_GATEWAY_API_PORT: ${GATEWAY_API_PORT}
    volumes:
      - ./spa/src:/app/src
      - ./spa/public:/app/public
    depends_on:
      - gateway
    networks:
      - app-tier
  simulator:
    container_name: fleetmetrics-simulator
    build: 
      context: .
      dockerfile: ./simulator/Dockerfile
    environment:
      MQTT_PORT: ${GATEWAY_MQTT_PORT}
      MQTT_HOST: gateway
    volumes:
      - ./simulator/:/app
    depends_on:
      - gateway
    networks:
      - app-tier